### ISSUE TITLE
Allow custom @content to be passed into classes mixin

### ISSUE THREAD

**Issue by djgrant** [djgrant/chameleon#7]
Allow the custom @content to be passed into the classes mixin:

``` scss
@include classes('my-selector', $on: 'tablet') {
  padding: 20px;
}
```

If a placeholder exists with the same selector name, both the styles of @content and %placeholder will be used. 

(It's not possible to test if @content is passed so whether it's ideal or not this is the behaviour we're getting).
